(() => {
  const API = 'http://127.0.0.1:8787';
  const state = { data: {}, scenario: '展览策划' };
  const $ = (selector, root = document) => root.querySelector(selector);
  const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
  const esc = (value = '') => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const token = () => sessionStorage.getItem('yingge-admin-token') || '';
  const showNotice = (message, error = false) => { const el = $('#globalNotice'); el.hidden = !message; el.textContent = message || ''; el.classList.toggle('error', error); if (message) setTimeout(() => { el.hidden = true; }, 5000); };
  async function api(path, options = {}) { const headers = { ...(options.body ? {'content-type':'application/json'} : {}), ...(token() ? {'Authorization': `Bearer ${token()}`} : {}), ...(options.headers || {}) }; const response = await fetch(`${API}${path}`, { ...options, headers }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || `请求失败 ${response.status}`); return data; }
  const formatNumber = value => new Intl.NumberFormat('zh-CN').format(Number(value || 0));
  const date = value => value ? new Date(value).toLocaleDateString('zh-CN', {month:'short', day:'numeric'}) : '暂无';
  function metric(label, value, note, accent = false) { return `<div class="metric"><label>${esc(label)}</label><strong class="${accent ? 'metric-accent' : ''}">${esc(value)}</strong><small>${esc(note)}</small></div>`; }
  function renderMetrics() { const summary = state.data.metrics?.summary || {}; const feedback = state.data.feedback?.metrics || {}; const readiness = state.data.readiness || {}; $('#metricGrid').innerHTML = [metric('累计问答', formatNumber(summary.requests), `成功 ${formatNumber(summary.successes)} 次`), metric('待处理问题', formatNumber((state.data.unanswered?.items || []).length), '点击内容审核进入'), metric('用户点踩', formatNumber(feedback.downvotes), '需要人工复核', Boolean(feedback.downvotes)), metric('知识版本', state.data.health?.knowledge_version || '未知', readiness.label || '等待检查')].join(''); $('#insightKpis').innerHTML = [metric('独立问题', formatNumber(feedback.total), '已写入服务记录'), metric('聚类主题', formatNumber((state.data.clusters?.clusters || []).length), '可转为策划选题'), metric('证据完整率', `${Math.round((summary.citation_integrity_rate || 0) * 100)}%`, '回答引用通过率')].join(''); }
  function renderOverview() { renderMetrics(); const unanswered = state.data.unanswered?.items || []; const tasks = state.data.tasks?.items || []; const clusters = state.data.clusters?.clusters || []; const signals = [unanswered.length ? `<i></i><strong>${unanswered.length} 个问题还没有知识答案</strong><span>建议转入内容审核</span>` : `<i></i><strong>暂无开放问题</strong><span>继续观察访客提问</span>`, tasks.length ? `<i></i><strong>${tasks.length} 个知识任务等待补证</strong><span>可进入内容审核推进</span>` : `<i></i><strong>知识任务队列为空</strong><span>当前没有补证任务</span>`, clusters.length ? `<i></i><strong>已识别 ${clusters.length} 个访客主题</strong><span>可以交给小槌做项目策划</span>` : `<i></i><strong>访客主题尚未形成聚类</strong><span>去访客洞察运行聚类</span>`]; $('#signalList').innerHTML = signals.map(item => `<div class="signal">${item}</div>`).join(''); const readiness = state.data.readiness || {}; $('#readinessBadge').textContent = readiness.label || '待检查'; $('#readinessSummary').textContent = readiness.status === 'ready' ? '当前知识服务通过发布闸门，可以继续进行本地验收。' : '知识服务需要检查配置或补充评测。'; const checks = readiness.checks || []; $('#miniBars').innerHTML = checks.slice(0, 4).map(item => `<div class="mini-bar"><span>${esc(item.label)}</span><div class="bar-track"><i style="width:${Math.round(Number(item.value || 0) * 100)}%"></i></div><em>${Math.round(Number(item.value || 0) * 100)}%</em></div>`).join('') || '<div class="empty-state-line">尚未读取评测数据</div>'; }
  function renderInsights() { const clusters = state.data.clusters?.clusters || []; $('#clusterRows').innerHTML = clusters.length ? clusters.map(item => `<tr><td><span class="priority priority-${esc(item.priority || 'P2')}">${esc(item.priority || 'P2')}</span></td><td><strong>${esc(item.label || item.name || '未命名主题')}</strong><br><span class="muted">${esc(item.summary || item.description || '')}</span></td><td>${formatNumber(item.count || item.question_count)}</td><td>${date(item.last_seen || item.updated_at)}</td></tr>`).join('') : '<tr><td colspan="4" class="empty-row">还没有形成问题聚类</td></tr>'; const feedback = state.data.feedback?.items || []; $('#feedbackList').innerHTML = feedback.length ? feedback.slice(0, 8).map(item => `<div class="feedback-item"><p>${esc(item.question || item.message || '未提供问题内容')}</p><div class="feedback-meta"><span>${esc(item.reason || item.status || '待复核')}</span><span>${date(item.created_at || item.updated_at)}</span></div></div>`).join('') : '<div class="empty-state-line">当前没有需要人工关注的反馈</div>'; }
  function renderTasks() { const unanswered = state.data.unanswered?.items || []; const tasks = state.data.tasks?.items || []; $('#unansweredCount').textContent = unanswered.length; $('#knowledgeCount').textContent = tasks.length; $('#unansweredList').innerHTML = unanswered.length ? unanswered.map(item => `<div class="task-item"><p>${esc(item.question)}</p><div class="task-meta"><span>${esc(item.intent || 'general')}</span><span>${date(item.last_seen)}</span></div><button class="button button-outline" data-promote="${esc(item.question)}" data-app="${esc(item.app_id || 'yingge-h5')}" type="button">转为知识任务</button></div>`).join('') : '<div class="empty-state-line">暂无待处理问题</div>'; $('#knowledgeList').innerHTML = tasks.length ? tasks.map(item => `<div class="task-item"><p>${esc(item.question)}</p><div class="task-meta"><span>${esc(item.status || 'open')}</span><span>${date(item.created_at)}</span></div><button class="button button-outline" data-close-task="${esc(item.task_id)}" type="button">标记已处理</button></div>`).join('') : '<div class="empty-state-line">暂无知识补证任务</div>'; }
  function renderEvaluation() { const evaluation = state.data.evaluation || {}; const readiness = state.data.readiness || {}; $('#evaluationStatus').textContent = readiness.label || evaluation.status || '尚未评测'; $('#evaluationScore').innerHTML = `<strong>${Math.round(Number(evaluation.recall_at_6 || 0) * 100)}%</strong><span>检索 Recall@6<br>目标 ≥ 95%</span>`; const checks = readiness.checks || []; $('#checkList').innerHTML = checks.length ? checks.map(item => `<div class="check-item"><i>${item.pass ? '✓' : '!'}</i><span>${esc(item.label)}</span><em>${Math.round(Number(item.value || 0) * 100)}%</em></div>`).join('') : '<div class="empty-state-line">暂无评测结果</div>'; }
  async function loadAll() { $('#systemStatus').textContent = '正在读取知识服务'; try { const [health, metrics, feedback, clusters, unanswered, tasks, readiness, evaluation] = await Promise.all([api('/api/health'), api('/api/admin/metrics'), api('/api/admin/feedback'), api('/api/admin/feedback/clusters'), api('/api/admin/unanswered'), api('/api/admin/knowledge-tasks'), api('/api/admin/evaluation/readiness'), api('/api/admin/evaluation')]); Object.assign(state.data, {health, metrics, feedback, clusters, unanswered, tasks, readiness, evaluation}); renderOverview(); renderInsights(); renderTasks(); renderEvaluation(); $('#systemStatus').textContent = '知识服务已连接'; $('.system-dot').style.background = '#68a66c'; } catch (error) { $('#systemStatus').textContent = '知识服务未连接'; showNotice(error.message, true); } }
  function switchView(view) { $$('.rail-link').forEach(button => button.classList.toggle('is-active', button.dataset.view === view)); $$('.view').forEach(panel => panel.classList.toggle('is-active', panel.dataset.panel === view)); const titles = {overview:'工作台总览', insights:'访客洞察', content:'内容审核', planner:'项目策划', evaluation:'知识评测'}; $('#viewTitle').textContent = titles[view] || '运营工作台'; window.scrollTo({top:0, behavior:'smooth'}); }
  async function askPlanner(event) { event.preventDefault(); const input = $('#plannerInput'); const message = input.value.trim(); if (!message) { showNotice('先描述你的项目目标和限制条件。', true); return; } const answer = $('#plannerAnswer'); answer.innerHTML = '<div class="empty-state-line">小槌正在查阅证据并整理方案…</div>'; const submit = $('#plannerForm button'); submit.disabled = true; try { const data = await api('/api/admin/test', {method:'POST', body:JSON.stringify({app_id:'yingge-h5', message:`你现在服务文化机构管理人员。当前策划场景：${state.scenario}。请围绕以下需求给出可执行建议，先给结论，再列目标、受众、内容结构、执行步骤、风险和需要核实的事实，并为事实附上[证据N]引用。需求：${message}`, context:{audience:'文化机构管理人员', detail_level:'deep', source_mode:'brief'}})}); const citations = (data.citations || []).map(item => `<a href="${esc(item.url || '#')}" target="_blank" rel="noreferrer">${esc(item.title || item.url || '查看来源')}</a>`).join(''); answer.innerHTML = `<div class="answer-block">${esc(data.answer || '暂时没有生成内容')}</div>${citations ? `<div class="citation-list"><strong>依据来源</strong>${citations}</div>` : ''}`; input.value = ''; } catch (error) { answer.innerHTML = `<div class="empty-state-line">${esc(error.message)}<br><small>请确认服务端已配置 DEEPSEEK_API_KEY，或先使用知识库离线功能。</small></div>`; } finally { submit.disabled = false; } }
  document.addEventListener('click', async event => { const viewButton = event.target.closest('[data-view]'); if (viewButton) switchView(viewButton.dataset.view); const go = event.target.closest('[data-go]'); if (go) switchView(go.dataset.go); const scenario = event.target.closest('[data-scenario]'); if (scenario) { state.scenario = scenario.dataset.scenario; $$('.scenario').forEach(item => item.classList.toggle('is-active', item === scenario)); $('#plannerMode').textContent = `${state.scenario}模式 · 证据优先`; } const promote = event.target.closest('[data-promote]'); if (promote) { try { await api('/api/admin/unanswered/promote', {method:'POST', body:JSON.stringify({app_id:promote.dataset.app, question:promote.dataset.promote})}); showNotice('已转为知识任务'); await loadAll(); } catch (error) { showNotice(error.message, true); } } const closeTask = event.target.closest('[data-close-task]'); if (closeTask) { try { await api('/api/admin/knowledge-tasks/status', {method:'POST', body:JSON.stringify({task_id:closeTask.dataset.closeTask, status:'closed'})}); showNotice('任务已标记完成'); await loadAll(); } catch (error) { showNotice(error.message, true); } } });
  $('#plannerForm').addEventListener('submit', askPlanner); $('#refreshAll').addEventListener('click', loadAll); $('#saveToken').addEventListener('click', () => { const value = $('#adminToken').value.trim(); if (value) sessionStorage.setItem('yingge-admin-token', value); else sessionStorage.removeItem('yingge-admin-token'); showNotice(value ? '管理 Token 已保存到当前会话' : '已清除当前会话 Token'); loadAll(); }); $('#runClusters').addEventListener('click', async () => { try { await api('/api/admin/feedback/clusters/run', {method:'POST', body:'{}'}); showNotice('问题聚类已重新计算'); await loadAll(); } catch (error) { showNotice(error.message, true); } }); $('#runEvaluation').addEventListener('click', async () => { try { await api('/api/admin/evaluation/run', {method:'POST', body:JSON.stringify({limit:6})}); showNotice('评测已完成'); await loadAll(); } catch (error) { showNotice(error.message, true); } });
  if (token()) $('#adminToken').value = token(); loadAll();
})();
